config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
  get 'gems' => 'gems#index'
  get 'transaction' => 'transactions#create'
  get 'history' => 'transactions#show'
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
 
  # This is caused by ActiveRecord already using a method named "transactions". 
  # To handle this issue, choose an appropriate alternative name for the association and specify the model class and foreign key manually.
  
   scope :spendable, -> { where(item_type: 0) }
   scope :purchasable, -> { where(item_type: 1) }

   def type
      self.item_type 
   end 
  

end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :item
  
  default_scope { order(created_at: :desc) }

  def get_date
        self.created_at.strftime("%m-%d (%I:%M%p)")
  end 

  def get_gem
        if (self.item.type == 0)
         " - " + self.item.gem.to_s
        else
          " + " + self.item.gem.to_s
        end
  end 

end

app/models/user.rb
class User < ApplicationRecord
    has_many :transactions
    has_many :items, through: :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


    # Now this is available to all views as well
    helper_method :current_user
    helper_method :items

    # We will have the first user be logged in by default
    # This function will now be available to all controllers 
    def current_user
        @User = User.find(3)
    end 
  
    def items 
       @Items = Item.all
    end 

end

app/controllers/gems_controller.rb
class GemsController < ApplicationController


    def index
        @User = current_user
    end 
    
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

    include TransactionsHelper

    def create
        # creation should be done here. Let's rethink how we should approach this task
        item = Item.find(params[:item])
        update_gem(item)
    end 

    def show
    end 
    


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/gems_helper.rb
module GemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper

    

    # initialize 3 items 
    





end

app/helpers/transactions_helper.rb
module TransactionsHelper

        #  t.integer  "user_id"
        #  t.integer  "item_id"


        def update_gem(item)
            # this is spendable Item.
            if (item.type == 0)
                if (current_user.gem >= item.gem)
                    Transaction.create!(user_id: current_user.id, item_id: item.id, accumulative: current_user.gem - item.gem)
                    current_user.update_attribute(:gem, current_user.gem - item.gem)
                    flash[:success] = "Purchased " + item.name.to_s + " : " + item.gem.to_s + " Gems deducted from your account"
                else    
                     flash[:warning] = "Purchase not complete. Please make sure you have enough gems"
                end
            # this is purchasable Item (more gems !)
            elsif(item.type == 1)
                Transaction.create!(user_id: current_user.id, item_id: item.id, accumulative: current_user.gem + item.gem)
                current_user.update_attribute(:gem, current_user.gem + item.gem)
                flash[:success] = "Purchased Item " + item.gem.to_s + " Gems" 
            end
            redirect_to gems_path
        end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gems/index.html.erb
<div class="col-sm-6 col-sm-offset-3">

    <div class="row text-center">
        <div class="col-sm-4">
            <%= link_to 'Home', root_path, class: 'btn btn-default top-15' %>
        </div>
        <div class="col-sm-4">
                 <h2> Gem Store </h2>
        </div>
        <div class="col-sm-4">
            <%= link_to 'History', history_path, class: 'btn btn-default top-15' %>
        </div>
    </div>

    <div class="row text-center">
        <h1> <%= current_user.gem %> </h1>
        <small> Gems in Possession</small> 
    </div>
    
    <hr>

    <ul class="gem-table"> 
        <% items.purchasable.each do |item| %>
            <li> <%= item.gem %> <small> Gems </small>
            <%= link_to number_to_currency(item.price), transaction_path(:item => item), class: 'btn btn-default float-right' %>
        <% end %>
    </ul> 

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gemstore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> text-center"><%= value %></div>
      <% end %>


       <%= yield %>
    </div>
  </body>
</html>

app/views/transactions/show.html.erb
<div class="col-sm-6 col-sm-offset-3">

    <div class="panel panel-default">
        <div class="panel-heading text-center"> <h1> History </h1> </div>


            <table class="table text-center">
                <th>
                    <tr>
                        <td class="col-md-2"> Date</td>
                        <td class="col-md-2"> Item Description </td>
                        <td class="col-md-2"> Change</td>
                        <td class="col-md-2"> Accumulative </td>
                    </tr>
                </th>


           <% current_user.transactions.each do |transaction| %>
            <tr>
                <td><%= transaction.get_date %> </td>
                <td><%= transaction.item.name %> </td>
                <td><%= transaction.get_gem %> </td>
                <td><%= transaction.accumulative %> </td>
            </tr>
           <% end %>
    
            </table>
    </div>

</div>

app/views/users/index.html.erb
<div class="row top-15 text-center">
    <h3> Hello, <%= current_user.name %> </h3>
</div>


    <div class="row top-15">
        <div class="col-sm-6 col-sm-offset-3 text-center">
            <%= link_to 'Gem Store', gems_path, class: 'btn btn-default' %>  
        </div>  
    </div>

    <hr>

    <div class="row text-center"> 
        <h3 class="center"> Purchase Items </h3> 
    </div>

    <!-- using scopes defined in item.rb -->
    <% items.spendable.each do |item| %>
        <div class='row top-15'>
            <div class="col-sm-6 col-sm-offset-3">
                <%= link_to item.name + " :: #{item.gem} Gems", transaction_path(:item => item), class: 'btn btn-default btn-lg btn-block', 
                data: { confirm: "Are you sure? It costs #{item.gem} " } %>
            </div>
        </div>
    <% end %>